### ISSUE TITLE
Iptables errror on jessie

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-dispatcher#112]
This is from the logs on my local jessie box, using latest docker-engine from the docker repo (1.9.?):

```
2016-01-05T09:44:44.235246+00:00 local1 pixelated.manager: INFO User test01 logged in successfully
2016-01-05T09:44:44.243008+00:00 local1 pixelated.proxy: INFO Successful login of user test01
2016-01-05T09:44:44.243474+00:00 local1 pixelated.proxy: INFO Starting agent for test01
2016-01-05T09:44:44.773369+00:00 local1 pixelated.manager: ERROR Unhandled Error during request: 500 Server Error: Internal Server Error ("Cannot start container d3642af5b736ca6dfd3b51a152ae
6e0b7708b5aa5cd75f2fb309a51100327e49: failed to create endpoint test01 on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0.0.0.0 --dport 5000 -j DNAT --to-destin
ation 0.0.0.0:4567 ! -i docker0: iptables: No chain/target/match by that name.#012 (exit status 1)")#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/pixelat
ed/manager/__init__.py", line 69, in wrapper#012    return callback(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 182, in _put_agent_state
#012    self._provider.start(user_cfg)#012  File "/usr/lib/python2.7/dist-packages/pixelated/provider/docker/__init__.py", line 275, in start#012    port_bindings={self._adapter.port(): ('0.
0.0.0', port)})#012  File "/usr/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped#012    return f(self, resource_id, *args, **kwargs)#012  File "/usr/lib/python2.7
/dist-packages/docker/api/container.py", line 343, in start#012    self._raise_for_status(res)#012  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 142, in _raise_for_status#0
12    raise errors.APIError(e, response, explanation=explanation)#012APIError: 500 Server Error: Internal Server Error ("Cannot start container d3642af5b736ca6dfd3b51a152ae6e0b7708b5aa5cd75f
2fb309a51100327e49: failed to create endpoint test01 on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0.0.0.0 --dport 5000 -j DNAT --to-destination 0.0.0.0:4567 ! -i docker0: iptables: No chain/target/match by that name.#012 (exit status 1)")
2016-01-05T09:44:44.789525+00:00 local1 pixelated.proxy: WARNING Login attempt with invalid credentials by user test01
2016-01-05T09:44:44.791234+00:00 local1 tornado.access: INFO 302 POST /auth/login (0.0.0.0) 727.98ms
2016-01-05T09:44:44.808684+00:00 local1 tornado.access: INFO 200 GET /auth/login (0.0.0.0) 1.86ms
2016-01-05T09:44:44.983733+00:00 local1 pixelated.proxy: INFO User test01 logged out


```

**Comment by varac** [comment]
Using docker.io version1.6.2~dfsg1-1~bpo8+1  from jessie-backports, i get: 

```
2016-01-05T10:29:10.224197+00:00 local1 tornado.access: INFO 200 GET /auth/login?next=%2Ffonts%2FOpenSans.woff (0.0.0.0) 0.96ms
2016-01-05T10:29:10.231031+00:00 local1 tornado.access: INFO 200 GET /auth/login?next=%2Ffonts%2FOpenSans-Light.woff (0.0.0.0) 0.85ms
2016-01-05T10:30:10.067313+00:00 local1 pixelated.manager: ERROR Unhandled Error during request: #012Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 69, in wrapper#012    return callback(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/pixelated/manager/__init__.py", line 159, in _get_agent#012    self._provider.status(name)#012  File "/usr/lib/python2.7/dist-packages/pixelated/provider/base_provider.py", line 101, in status#012    if name in self.list_running():#012  File "/usr/lib/python2.7/dist-packages/pixelated/provider/docker/__init__.py", line 300, in list_running#012    self._ensure_initialized()#012  File "/usr/lib/python2.7/dist-packages/pixelated/provider/base_provider.py", line 69, in _ensure_initialized#012    raise ProviderInitializingException()#012ProviderInitializingException
2016-01-05T10:30:10.080274+00:00 local1 pixelated.proxy: ERROR Login attempt while service not available by user: test21
```

**Comment by varac** [comment]
As we don't focus on vagrant until we get rid of docker, i'll close this.
